name: "build"
on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:
jobs:
  launch-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-java@v5.2.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Test Gradle
        run: |
          chmod +x ./gradlew
          cp src/main/resources/test_config.example.yml src/main/resources/test_config.yml
          cp src/main/resources/mimic-iv_subjectids_tsids_short.csv src/main/resources/mimic-iv_subjectids_tsids.csv
          ./downloadDataset.sh smartbench small.tar.gz
          ./downloadDataset.sh mimic 1692200.dump
          docker compose up -d
          sleep 120
          ./gradlew test --tests "it.unibo.tests.ci*"

  release:
    needs:
      - launch-linux
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install Node
        uses: actions/setup-node@v6.2.0
        with:
          node-version-file: package.json
      - uses: actions/setup-java@v5.2.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Deploy
        run: |
          chmod +x ./gradlew
          ./gradlew shadowJar
          mkdir -p dist/
          cp build/libs/* dist/
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
